version: '3.3'

services:
   db:
     image: mariadb
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

   phpmyadmin:
     image: corbinu/docker-phpmyadmin
     links:
       - db:mysql
     ports:
       - 8181:80
     environment:
        MYSQL_PORT_3306_TCP_ADDR: db
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: password
volumes:
    db_data: {}